"use client";

import { ReactNode } from "react";
import { LinkedInData, normalizeLinkedInData } from "@/Components/modulos/LinkedInForm";

const plain = (value: string) => value.replace(/<[^>]*>/g, " ").replace(/&nbsp;/g, " ").replace(/\s+/g, " ").trim();
const hasHtml = (value: string) => Boolean(plain(value));
const validUrl = (value: string) => { try { const url = new URL(value); return url.protocol === "http:" || url.protocol === "https:"; } catch { return false; } };
function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><h2 className="text-xl font-semibold text-slate-950 sm:text-2xl">{title}</h2><div className="mt-6">{children}</div></section>; }
function Rich({ value }: { value: string }) { return <div className="prose prose-slate max-w-none text-sm leading-7 text-slate-600" dangerouslySetInnerHTML={{ __html: value }}/>; }
function Chips({ values }: { values: string[] }) { return <div className="flex flex-wrap gap-2">{values.filter(Boolean).map((value,index)=><span key={`${value}-${index}`} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-medium text-slate-700">{value}</span>)}</div>; }

export default function LinkedinPresentation({ data }: { data: unknown }) {
  const d: LinkedInData = normalizeLinkedInData(data);
  const objectives = d.objectives.filter(item=>item.value);
  const profileVisible = Boolean(d.profileCover||d.profilePhoto||d.profileName||d.professionalTitle||d.location||d.currentCompany||d.followers||d.connections||hasHtml(d.aboutProfile));
  const featured = d.featuredItems.filter(item=>item.name||item.purpose||item.destination||item.cta||item.imageUrl);
  const frequencies = d.frequencyItems.filter(item=>item.format||item.quantity||item.observation);
  const territories = d.editorialTerritories.filter(item=>item.name||item.purpose||item.description||item.recommendedFormats.some(v=>v.value));
  const newsletterVisible = Boolean(d.newsletter.provisionalName||d.newsletter.strategicRole||d.newsletter.periodicity||d.newsletter.startPhase||d.newsletter.territories.some(v=>v.value)||hasHtml(d.newsletter.predominantStructure)||d.newsletter.ctaGuideline);
  const structureVisible = Boolean(hasHtml(d.predominantStructure)||hasHtml(d.languageDirection)||d.languageRestrictions.some(v=>v.value)||hasHtml(d.visualDirection)||d.visualElements.some(v=>v.value)||d.visualRestrictions.some(v=>v.value)||d.visualReferences.some(v=>v.image));
  const conversionVisible = Boolean(d.acquisitionGuideline||d.commentsGuideline||d.privateMessagesGuideline||d.privateMessageSteps.some(v=>v.value)||Object.values(d.conversionStages).some(v=>v.action||v.destination)||d.ctaGuideline);
  const integrationVisible = Boolean(d.ecosystemRole||d.receivesFrom.some(v=>v.value)||d.directsTo.some(v=>v.value)||hasHtml(d.contentAdaptation));
  const indicators = d.indicatorCategories.filter(category=>category.name||category.indicators.some(v=>v.value));
  return <div className="space-y-6">
    {(hasHtml(d.strategicRole)||objectives.length>0)&&<Section title="Visão estratégica"><div className="space-y-6">{hasHtml(d.strategicRole)&&<Rich value={d.strategicRole}/>} {objectives.length>0&&<div><h3 className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-slate-400">Objetivos principais</h3><ul className="space-y-2">{objectives.map(item=><li key={item.id} className="flex gap-3 text-sm text-slate-700"><span aria-hidden="true" className="text-blue-700">◎</span>{item.value}</li>)}</ul></div>}</div></Section>}
    {profileVisible&&<Section title="Perfil profissional"><div className="overflow-hidden rounded-3xl border border-slate-200"><div className="aspect-[4/1] bg-slate-100">{d.profileCover&&<img src={d.profileCover} alt="Capa do perfil" className="h-full w-full object-cover"/>}</div><div className="relative px-5 pb-6 pt-14 sm:px-8"><div className="absolute -top-12 h-24 w-24 overflow-hidden rounded-full border-4 border-white bg-slate-900">{d.profilePhoto&&<img src={d.profilePhoto} alt={`Foto de ${d.profileName||"perfil"}`} className="h-full w-full object-cover"/>}</div><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div>{d.profileName&&<h3 className="text-xl font-semibold text-slate-950">{d.profileName}</h3>}{d.professionalTitle&&<p className="mt-1 text-sm text-slate-700">{d.professionalTitle}</p>}{(d.location||d.currentCompany)&&<p className="mt-1 text-xs text-slate-500">{[d.location,d.currentCompany].filter(Boolean).join(" · ")}</p>}{(d.followers||d.connections)&&<p className="mt-2 text-xs font-semibold text-blue-700">{[d.followers&&`${d.followers} seguidores`,d.connections&&`${d.connections} conexões`].filter(Boolean).join(" · ")}</p>}</div><div aria-hidden="true" className="flex gap-2"><span className="rounded-full bg-blue-700 px-4 py-2 text-xs font-semibold text-white">Conectar</span><span className="rounded-full border border-blue-700 px-4 py-2 text-xs font-semibold text-blue-700">Mensagem</span></div></div>{hasHtml(d.aboutProfile)&&<div className="mt-6 border-t border-slate-100 pt-5"><Rich value={d.aboutProfile}/></div>}{featured.length>0&&<div className="mt-6 grid gap-3 sm:grid-cols-2">{featured.slice(0,2).map(item=><div key={item.id} className="rounded-2xl border border-slate-200 p-3">{item.imageUrl&&<img src={item.imageUrl} alt={item.name||"Item em destaque"} className="mb-3 aspect-video w-full rounded-xl object-cover"/>}<p className="text-sm font-semibold">{item.name}</p></div>)}</div>}</div></div></Section>}
    {featured.length>0&&<Section title="Itens em destaque"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featured.map(item=>{const card=<div className="h-full overflow-hidden rounded-2xl border border-slate-200 bg-slate-50">{item.imageUrl&&<img src={item.imageUrl} alt={item.name||"Item em destaque"} className="aspect-video w-full object-cover"/>}<div className="p-4">{item.name&&<h3 className="font-semibold text-slate-950">{item.name}</h3>}{item.purpose&&<p className="mt-2 text-sm leading-6 text-slate-600">{item.purpose}</p>}{item.cta&&<p className="mt-4 text-xs font-bold text-blue-700">{item.cta} →</p>}</div></div>;return validUrl(item.destination)?<a key={item.id} href={item.destination} target="_blank" rel="noopener noreferrer">{card}</a>:<div key={item.id}>{card}</div>})}</div></Section>}
    {frequencies.length>0&&<Section title="Formatos e frequência"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{frequencies.map(item=><div key={item.id} className="rounded-2xl border border-slate-200 p-4"><h3 className="font-semibold">{item.format==="Post de texto"?"Texto autoral":item.format==="Carrossel"?"Carrossel em documento":item.format}</h3>{(item.quantity||item.period)&&<p className="mt-2 text-sm font-semibold text-blue-700">{item.quantity||"—"}× {item.period}</p>}{item.observation&&<p className="mt-2 text-xs leading-5 text-slate-500">{item.observation}</p>}</div>)}</div></Section>}
    {(territories.length>0||hasHtml(d.editorialApproach))&&<Section title="Estratégia editorial"><div className="space-y-6">{hasHtml(d.editorialApproach)&&<Rich value={d.editorialApproach}/>}<div className="grid gap-4 md:grid-cols-2">{territories.map(item=><article key={item.id} className="rounded-2xl bg-slate-50 p-5">{item.name&&<h3 className="font-semibold">{item.name}</h3>}{item.purpose&&<p className="mt-2 text-sm font-medium text-blue-700">{item.purpose}</p>}{item.description&&<p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p>}<div className="mt-4"><Chips values={item.recommendedFormats.map(v=>v.value)}/></div></article>)}</div></div></Section>}
    {newsletterVisible&&<Section title="Newsletter"><div className="rounded-2xl bg-slate-50 p-5">{d.newsletter.provisionalName&&<h3 className="text-lg font-semibold">{d.newsletter.provisionalName}</h3>}<div className="mt-3 flex flex-wrap gap-2">{d.newsletter.periodicity&&<span className="rounded-full bg-white px-3 py-1 text-xs">{d.newsletter.periodicity}</span>}{d.newsletter.startPhase&&<span className="rounded-full bg-white px-3 py-1 text-xs">{d.newsletter.startPhase}</span>}</div>{d.newsletter.strategicRole&&<p className="mt-4 text-sm leading-6 text-slate-600">{d.newsletter.strategicRole}</p>}<div className="mt-4"><Chips values={d.newsletter.territories.map(v=>v.value)}/></div>{(hasHtml(d.newsletter.predominantStructure)||d.newsletter.ctaGuideline)&&<details className="mt-5"><summary className="cursor-pointer text-sm font-semibold text-blue-700">Ver estrutura e CTA</summary><div className="mt-3 space-y-3">{hasHtml(d.newsletter.predominantStructure)&&<Rich value={d.newsletter.predominantStructure}/>} {d.newsletter.ctaGuideline&&<p className="text-sm text-slate-600">{d.newsletter.ctaGuideline}</p>}</div></details>}</div></Section>}
    {structureVisible&&<Section title="Estrutura, linguagem e direção visual"><div className="grid gap-6 lg:grid-cols-3">{hasHtml(d.predominantStructure)&&<div><h3 className="mb-3 font-semibold">Estrutura do conteúdo</h3><Rich value={d.predominantStructure}/></div>}<div>{hasHtml(d.languageDirection)&&<><h3 className="mb-3 font-semibold">Direção de linguagem</h3><Rich value={d.languageDirection}/></>} {d.languageRestrictions.filter(v=>v.value).map(v=><p key={v.id} className="mt-2 flex gap-2 text-sm text-slate-700"><span className="font-bold text-red-500">×</span>{v.value}</p>)}</div><div>{hasHtml(d.visualDirection)&&<><h3 className="mb-3 font-semibold">Direção visual</h3><Rich value={d.visualDirection}/></>}<div className="mt-3"><Chips values={d.visualElements.map(v=>v.value)}/></div>{d.visualRestrictions.filter(v=>v.value).map(v=><p key={v.id} className="mt-2 flex gap-2 text-sm text-slate-700"><span className="font-bold text-red-500">×</span>{v.value}</p>)}</div></div>{d.visualReferences.some(v=>v.image)&&<div className="mt-6 grid gap-3 sm:grid-cols-3">{d.visualReferences.filter(v=>v.image).map(v=><img key={v.id} src={v.image} alt={v.title||"Referência visual"} className="aspect-video w-full rounded-xl object-cover"/>)}</div>}</Section>}
    {conversionVisible&&<Section title="Aquisição, relacionamento e conversão"><div className="grid gap-5 md:grid-cols-2">{[["Diretriz de aquisição",d.acquisitionGuideline],["Diretriz de comentários",d.commentsGuideline],["Diretriz de mensagens privadas",d.privateMessagesGuideline],["Diretriz de CTA",d.ctaGuideline]].filter(([,value])=>value).map(([label,value])=><div key={label}><h3 className="font-semibold">{label}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{value}</p></div>)}</div>{d.privateMessageSteps.some(v=>v.value)&&<div className="mt-6 flex flex-col gap-3 md:flex-row">{d.privateMessageSteps.filter(v=>v.value).map((v,index)=><div key={v.id} className="flex-1 rounded-2xl bg-slate-50 p-4"><span className="text-xs font-bold text-blue-700">ETAPA {String(index+1).padStart(2,"0")}</span><p className="mt-2 text-sm text-slate-700">{v.value}</p></div>)}</div>}<div className="mt-6 grid gap-3 md:grid-cols-3">{([["Descoberta e aprofundamento","discovery"],["Reconhecimento do problema","problem"],["Intenção comercial","commercial"]] as const).map(([label,key])=>{const item=d.conversionStages[key];return item.action||item.destination?<div key={key} className="rounded-2xl border p-4"><h3 className="text-sm font-semibold">{label}</h3>{item.action&&<p className="mt-3 text-sm text-slate-700">{item.action}</p>}{item.destination&&<p className="mt-2 text-xs text-blue-700">→ {item.destination}</p>}</div>:null})}</div></Section>}
    {integrationVisible&&<Section title="Integração com outros canais"><div className="flex flex-col items-stretch gap-3 text-center md:flex-row md:items-center"><div className="flex-1 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Recebe de</p><Chips values={d.receivesFrom.map(v=>v.value)}/></div><span aria-hidden="true" className="rotate-90 text-slate-400 md:rotate-0">→</span><div className="rounded-2xl bg-blue-700 px-6 py-4 font-semibold text-white">LinkedIn</div><span aria-hidden="true" className="rotate-90 text-slate-400 md:rotate-0">→</span><div className="flex-1 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Direciona para</p><Chips values={d.directsTo.map(v=>v.value)}/></div></div>{d.ecosystemRole&&<p className="mt-5 text-sm leading-6 text-slate-600">{d.ecosystemRole}</p>}{hasHtml(d.contentAdaptation)&&<div className="mt-5 border-t pt-5"><Rich value={d.contentAdaptation}/></div>}</Section>}
    {indicators.length>0&&<Section title="Indicadores"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{indicators.map(category=><div key={category.id} className="rounded-2xl bg-slate-50 p-5"><h3 className="font-semibold">{category.name}</h3><ul className="mt-3 space-y-2">{category.indicators.filter(v=>v.value).map(v=><li key={v.id} className="text-sm text-slate-600">• {v.value}</li>)}</ul></div>)}</div></Section>}
  </div>;
}
