import { normalizeTikTokData } from "@/Components/modulos/TikTokForm";
import { PresentationHeader } from "./PresentationHeader";
import { RichText } from "./RichText";
import { ModuleIcon } from "./ModuleIcon";
import { SectionCard, EmptyState } from "./ChannelPresentationShared";

const hasText = (value: unknown): value is string => typeof value === "string" && value.trim().length > 0;
const colors = ["bg-slate-950", "bg-slate-600", "bg-slate-400", "bg-slate-300"];

function Distribution({ items }: { items: Array<{ id: string; name: string; percentage: string }> }) {
  const valid = items.map((item, index) => ({ ...item, index, number: Number(item.percentage) })).filter((item) => hasText(item.percentage) && Number.isFinite(item.number) && item.number > 0);
  if (!valid.length) return null;
  return <div className="mb-7"><div className="flex h-2.5 overflow-hidden rounded-full bg-slate-100">{valid.map((item) => <span key={item.id} title={`${item.name}: ${item.percentage}%`} style={{ width: `${Math.min(item.number, 100)}%` }} className={colors[item.index % colors.length]} />)}</div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs text-slate-500">{valid.map((item) => <span key={item.id}>{item.name} · {item.percentage}%</span>)}</div></div>;
}

export default function TiktokPresentation({ data }: { data: unknown }) {
  const d = normalizeTikTokData(data);
  const objectives = d.objectives.filter((item) => hasText(item.value));
  const profileValues = [d.profileImageUrl, d.username, d.profileName, d.bio, d.followingCount, d.followersCount, d.likesCount, d.mainLink];
  const hasProfile = profileValues.some(hasText);
  const fronts = d.contentFronts.filter((item) => hasText(item.name) || hasText(item.percentage) || hasText(item.description));
  const frequency = d.frequencyItems.filter((item) => hasText(item.format) || hasText(item.quantity) || hasText(item.period) || hasText(item.observation));
  const visualElements = d.visualElements.filter((item) => hasText(item.value));
  const visualAvoid = d.visualAvoidItems.filter((item) => hasText(item.value));
  const visualReferences = d.visualReferences.filter((item) => hasText(item.image));
  const conversion = [["Descoberta", d.conversion.discovery], ["Consideração", d.conversion.consideration], ["Decisão", d.conversion.decision]] as const;
  const visibleConversion = conversion.filter(([, item]) => hasText(item.action) || hasText(item.destination));
  const receives = d.receivesFrom.filter((item) => hasText(item.value));
  const directs = d.directsTo.filter((item) => hasText(item.value));
  const indicators = d.indicatorCategories.map((item) => ({ ...item, indicators: item.indicators.filter((indicator) => hasText(indicator.name)) })).filter((item) => hasText(item.name) || item.indicators.length > 0);
  const hasStrategy = hasText(d.strategicRole) || objectives.length > 0;
  const hasFormats = hasText(d.mainFormats) || hasText(d.editorialTerritories);
  const hasStructure = hasText(d.videoStructure) || hasText(d.languageAndRetention);
  const hasVisual = hasText(d.visualGuideline) || visualElements.length > 0 || visualAvoid.length > 0 || visualReferences.length > 0;
  const hasConversion = visibleConversion.length > 0 || hasText(d.ctaGuideline) || hasText(d.ecosystemRole) || receives.length > 0 || directs.length > 0;
  const hasAny = hasStrategy || hasProfile || fronts.length > 0 || frequency.length > 0 || hasFormats || hasStructure || hasVisual || hasConversion || indicators.length > 0;
  const username = d.username && (d.username.startsWith("@") ? d.username : `@${d.username}`);

  return <article className="divide-y divide-slate-100 overflow-hidden rounded-[2rem] bg-white shadow-sm ring-1 ring-slate-200">
    <PresentationHeader area="Estratégia Editorial e Distribuição de Conteúdo" title="TikTok" slug="tiktok" />

    {hasStrategy && <SectionCard title="Visão estratégica"><div className="space-y-9">{hasText(d.strategicRole) && <div className="max-w-4xl border-l-2 border-slate-900 pl-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Papel estratégico do TikTok</p><RichText content={d.strategicRole} className="mt-4 text-base leading-8 text-slate-700" /></div>}{objectives.length > 0 && <div><h3 className="font-serif text-xl font-semibold text-slate-950">Objetivos principais</h3><div className="mt-5 grid gap-4 md:grid-cols-2">{objectives.map((item) => <div key={item.id} className="flex items-start gap-3"><span className="mt-0.5 text-slate-500"><ModuleIcon slug="objetivos-do-projeto" /></span><p className="text-sm leading-7 text-slate-700">{item.value}</p></div>)}</div></div>}</div></SectionCard>}

    {hasProfile && <SectionCard title="Perfil do TikTok"><div className="mx-auto max-w-3xl overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="p-5 sm:p-8"><div className="flex items-start gap-4 sm:gap-6">{hasText(d.profileImageUrl) && <img src={d.profileImageUrl} alt={d.profileName ? `Foto de ${d.profileName}` : "Foto do perfil do TikTok"} className="h-20 w-20 shrink-0 rounded-full object-cover ring-1 ring-slate-200 sm:h-24 sm:w-24" />}<div className="min-w-0 flex-1">{hasText(d.profileName) && <p className="break-words text-xl font-bold text-slate-950">{d.profileName}</p>}{username && <p className="mt-0.5 break-words text-sm text-slate-500">{username}</p>}<div aria-hidden="true" className="mt-4 flex gap-2"><span className="rounded-md bg-slate-950 px-8 py-2 text-sm font-semibold text-white">Seguir</span><span className="rounded-md border border-slate-200 px-3 py-2 text-slate-600">↗</span></div></div></div>{[d.followingCount, d.followersCount, d.likesCount].some(hasText) && <div className="mt-6 grid grid-cols-3 gap-2 text-center">{[[d.followingCount,"Seguindo"],[d.followersCount,"Seguidores"],[d.likesCount,"Curtidas"]].map(([value,label]) => hasText(value) && <div key={label}><p className="font-bold text-slate-950">{value}</p><p className="text-xs text-slate-500">{label}</p></div>)}</div>}{hasText(d.bio) && <p className="mt-5 whitespace-pre-wrap text-sm leading-6 text-slate-700">{d.bio}</p>}{hasText(d.mainLink) && <p className="mt-2 max-w-full break-all text-sm font-semibold text-slate-700">↗ {d.mainLink}</p>}</div><div aria-hidden="true" className="grid grid-cols-3 gap-0.5 border-t border-slate-200 bg-slate-200">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="aspect-[9/14] bg-[linear-gradient(145deg,#f8fafc,#e2e8f0)]" />)}</div></div></SectionCard>}

    {fronts.length > 0 && <SectionCard title="Estratégia de conteúdo"><Distribution items={fronts} /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{fronts.map((item) => <div key={item.id} className="rounded-2xl border border-slate-200 p-5">{hasText(item.percentage) && <p className="text-2xl font-semibold text-slate-950">{item.percentage}%</p>}{hasText(item.name) && <h3 className="mt-2 font-serif text-xl font-semibold text-slate-950">{item.name}</h3>}{hasText(item.description) && <p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.description}</p>}</div>)}</div></SectionCard>}

    {frequency.length > 0 && <SectionCard title="Frequência"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{frequency.map((item) => <div key={item.id} className="rounded-2xl border border-slate-200 p-4">{hasText(item.format) && <h3 className="font-semibold text-slate-950">{item.format}</h3>}{(hasText(item.quantity) || hasText(item.period)) && <p className="mt-3"><span className="text-2xl font-semibold text-slate-950">{item.quantity}{hasText(item.quantity) && hasText(item.period) && "×"}</span> <span className="text-sm text-slate-500">{item.period}</span></p>}{hasText(item.observation) && <p className="mt-3 whitespace-pre-wrap border-t border-slate-200 pt-3 text-sm leading-6 text-slate-600">{item.observation}</p>}</div>)}</div></SectionCard>}

    {hasFormats && <SectionCard title="Formatos e territórios"><div className="grid gap-8 md:grid-cols-2">{hasText(d.mainFormats) && <div><h3 className="font-serif text-xl font-semibold text-slate-950">Formatos principais</h3><RichText content={d.mainFormats} className="mt-4 text-sm leading-7 text-slate-700" /></div>}{hasText(d.editorialTerritories) && <div><h3 className="font-serif text-xl font-semibold text-slate-950">Territórios editoriais</h3><RichText content={d.editorialTerritories} className="mt-4 text-sm leading-7 text-slate-700" /></div>}</div></SectionCard>}
    {hasStructure && <SectionCard title="Estrutura dos vídeos"><div className="grid gap-8 md:grid-cols-2">{hasText(d.videoStructure) && <div><h3 className="font-serif text-xl font-semibold text-slate-950">Estrutura dos vídeos</h3><RichText content={d.videoStructure} className="mt-4 text-sm leading-7 text-slate-700" /></div>}{hasText(d.languageAndRetention) && <div><h3 className="font-serif text-xl font-semibold text-slate-950">Linguagem e retenção</h3><RichText content={d.languageAndRetention} className="mt-4 text-sm leading-7 text-slate-700" /></div>}</div></SectionCard>}

    {hasVisual && <SectionCard title="Direção visual"><div className="space-y-8">{hasText(d.visualGuideline) && <div className="max-w-4xl border-l-2 border-slate-400 pl-5"><RichText content={d.visualGuideline} className="text-base leading-7 text-slate-700" /></div>}<div className="grid gap-6 md:grid-cols-2">{visualElements.length > 0 && <div><h3 className="font-semibold text-slate-950">Elementos visuais</h3><div className="mt-3 flex flex-wrap gap-2">{visualElements.map((item) => <span key={item.id} className="rounded-full border border-slate-200 px-3 py-1.5 text-sm text-slate-700">◇ {item.value}</span>)}</div></div>}{visualAvoid.length > 0 && <div><h3 className="font-semibold text-red-600">O que evitar</h3><div className="mt-3 space-y-2">{visualAvoid.map((item) => <p key={item.id} className="flex gap-2 text-sm leading-6 text-slate-700"><span className="text-red-500">×</span>{item.value}</p>)}</div></div>}</div>{visualReferences.length > 0 && <div className="grid grid-cols-3 gap-3">{visualReferences.map((item) => <img key={item.id} src={item.image} alt="Referência visual do TikTok" className="aspect-[9/16] w-full rounded-xl object-cover ring-1 ring-slate-200" />)}</div>}</div></SectionCard>}

    {hasConversion && <SectionCard title="Conversão e integração"><div className="space-y-10">{visibleConversion.length > 0 && <div className="grid gap-4 md:grid-cols-3">{visibleConversion.map(([name,item]) => <div key={name} className="rounded-2xl border border-slate-200 p-5"><h3 className="font-serif text-lg font-semibold text-slate-950">{name}</h3>{hasText(item.action) && <div className="mt-4"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Ação esperada</p><p className="mt-2 text-sm leading-6 text-slate-700">{item.action}</p></div>}{hasText(item.destination) && <div className="mt-4 border-t border-slate-200 pt-4"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Destino ou continuidade</p><p className="mt-2 text-sm leading-6 text-slate-700">{item.destination}</p></div>}</div>)}</div>}{hasText(d.ctaGuideline) && <div className="max-w-4xl"><h3 className="font-semibold text-slate-950">Diretriz de CTA</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-700">{d.ctaGuideline}</p></div>}{(receives.length > 0 || hasText(d.ecosystemRole) || directs.length > 0) && <div className="grid gap-3 lg:grid-cols-[1fr_auto_1.15fr_auto_1fr] lg:items-stretch">{receives.length > 0 && <div className="rounded-2xl border border-slate-200 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Recebe de</p>{receives.map((item) => <p key={item.id} className="mt-2 text-sm text-slate-700">{item.value}</p>)}</div>}{receives.length > 0 && <span aria-hidden="true" className="self-center text-center text-slate-400"><span className="lg:hidden">↓</span><span className="hidden lg:inline">→</span></span>}{hasText(d.ecosystemRole) && <div className="rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs font-semibold uppercase tracking-wider text-slate-300">TikTok no ecossistema</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{d.ecosystemRole}</p></div>}{directs.length > 0 && <span aria-hidden="true" className="self-center text-center text-slate-400"><span className="lg:hidden">↓</span><span className="hidden lg:inline">→</span></span>}{directs.length > 0 && <div className="rounded-2xl border border-slate-200 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Direciona para</p>{directs.map((item) => <p key={item.id} className="mt-2 text-sm text-slate-700">{item.value}</p>)}</div>}</div>}</div></SectionCard>}

    {indicators.length > 0 && <SectionCard title="Indicadores"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{indicators.map((category) => <div key={category.id} className="rounded-2xl border border-slate-200 p-5">{hasText(category.name) && <h3 className="font-serif text-lg font-semibold text-slate-950">{category.name}</h3>}<ul className="mt-3 space-y-2">{category.indicators.map((item) => <li key={item.id} className="flex gap-2 text-sm leading-6 text-slate-700"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-slate-400" />{item.name}</li>)}</ul></div>)}</div></SectionCard>}
    {!hasAny && <EmptyState />}
  </article>;
}
