"use client";

import Link from "next/link";
import { ChangeEvent, Dispatch, ReactNode, SetStateAction, useState } from "react";
import RichTextEditor from "@/Components/RichTextEditor";
import { uploadPlanningMedia } from "@/lib/uploadPlanningMedia";

export type LinkedInTextItem = { id: string; value: string };
export type LinkedInFrequencyItem = { id: string; format: string; quantity: string; period: string; observation: string };
export type LinkedInFeaturedItem = { id: string; name: string; purpose: string; destination: string; cta: string; imageUrl: string };
export type LinkedInTerritory = { id: string; name: string; purpose: string; description: string; recommendedFormats: LinkedInTextItem[] };
export type LinkedInNewsletter = { provisionalName: string; strategicRole: string; periodicity: string; startPhase: string; territories: LinkedInTextItem[]; predominantStructure: string; ctaGuideline: string };
export type LinkedInVisualReference = { id: string; image: string; title: string };
export type LinkedInConversionStage = { action: string; destination: string };
export type LinkedInIndicatorCategory = { id: string; name: string; indicators: LinkedInTextItem[] };
export type LinkedInExternalReference = { id: string; title: string; link: string };

export type LinkedInData = {
  strategicRole: string; objectives: LinkedInTextItem[];
  profileCover: string; profilePhoto: string; profileName: string; professionalTitle: string; location: string; currentCompany: string; followers: string; connections: string; aboutProfile: string;
  featuredItems: LinkedInFeaturedItem[]; frequencyItems: LinkedInFrequencyItem[];
  editorialTerritories: LinkedInTerritory[]; editorialApproach: string; newsletter: LinkedInNewsletter;
  predominantStructure: string; languageDirection: string; languageRestrictions: LinkedInTextItem[]; visualDirection: string; visualElements: LinkedInTextItem[]; visualRestrictions: LinkedInTextItem[]; visualReferences: LinkedInVisualReference[];
  acquisitionGuideline: string; commentsGuideline: string; privateMessagesGuideline: string; privateMessageSteps: LinkedInTextItem[]; conversionStages: { discovery: LinkedInConversionStage; problem: LinkedInConversionStage; commercial: LinkedInConversionStage }; ctaGuideline: string;
  ecosystemRole: string; receivesFrom: LinkedInTextItem[]; directsTo: LinkedInTextItem[]; contentAdaptation: string;
  indicatorCategories: LinkedInIndicatorCategory[]; references: LinkedInExternalReference[];
};

const emptyStage = (): LinkedInConversionStage => ({ action: "", destination: "" });
export const initialLinkedInData: LinkedInData = {
  strategicRole: "", objectives: [], profileCover: "", profilePhoto: "", profileName: "", professionalTitle: "", location: "", currentCompany: "", followers: "", connections: "", aboutProfile: "", featuredItems: [], frequencyItems: [], editorialTerritories: [], editorialApproach: "",
  newsletter: { provisionalName: "", strategicRole: "", periodicity: "", startPhase: "", territories: [], predominantStructure: "", ctaGuideline: "" },
  predominantStructure: "", languageDirection: "", languageRestrictions: [], visualDirection: "", visualElements: [], visualRestrictions: [], visualReferences: [], acquisitionGuideline: "", commentsGuideline: "", privateMessagesGuideline: "", privateMessageSteps: [], conversionStages: { discovery: emptyStage(), problem: emptyStage(), commercial: emptyStage() }, ctaGuideline: "", ecosystemRole: "", receivesFrom: [], directsTo: [], contentAdaptation: "", indicatorCategories: [], references: [],
};

const record = (value: unknown): Record<string, unknown> => value && typeof value === "object" ? value as Record<string, unknown> : {};
const text = (value: unknown) => typeof value === "string" ? value : typeof value === "number" && Number.isFinite(value) ? String(value) : "";
const id = (value: unknown, fallback: string) => text(value) || fallback;
const list = (value: unknown, prefix: string): LinkedInTextItem[] => Array.isArray(value) ? value.map((item, index) => { const r = record(item); return { id: id(r.id, `${prefix}-${index}`), value: typeof item === "string" ? item : text(r.value) }; }).filter((item) => item.value) : [];
const stage = (value: unknown): LinkedInConversionStage => { const r = record(value); return { action: text(r.action), destination: text(r.destination) }; };

export function normalizeLinkedInData(value: unknown): LinkedInData {
  const r = record(value);
  const oldThemes = text(r.authorityThemes);
  const oldContents = list(r.contents, "legacy-content");
  const territories = Array.isArray(r.editorialTerritories) ? r.editorialTerritories.map((item, index) => { const t = record(item); return { id: id(t.id, `territory-${index}`), name: text(t.name), purpose: text(t.purpose), description: text(t.description), recommendedFormats: list(t.recommendedFormats, `territory-${index}-format`) }; }) : oldThemes ? [{ id: "legacy-authority-themes", name: oldThemes, purpose: "", description: "", recommendedFormats: [] }] : [];
  const frequencyItems = Array.isArray(r.frequencyItems) ? r.frequencyItems.map((item, index) => { const f = record(item); return { id: id(f.id, `frequency-${index}`), format: text(f.format), quantity: text(f.quantity), period: text(f.period) || "por semana", observation: text(f.observation) }; }) : [];
  const newsletter = record(r.newsletter);
  const conversions = record(r.conversionStages);
  return {
    ...initialLinkedInData,
    strategicRole: text(r.strategicRole), objectives: list(r.objectives, "objective"), profileCover: text(r.profileCover), profilePhoto: text(r.profilePhoto), profileName: text(r.profileName), professionalTitle: text(r.professionalTitle) || text(r.headline), location: text(r.location), currentCompany: text(r.currentCompany), followers: text(r.followers), connections: text(r.connections), aboutProfile: text(r.aboutProfile),
    featuredItems: Array.isArray(r.featuredItems) ? r.featuredItems.map((item, index) => { const f = record(item); return { id: id(f.id, `featured-${index}`), name: text(f.name), purpose: text(f.purpose), destination: text(f.destination), cta: text(f.cta), imageUrl: text(f.imageUrl) }; }) : [], frequencyItems,
    editorialTerritories: territories, editorialApproach: text(r.editorialApproach) || oldContents.map((item) => item.value).join("\n"), newsletter: { provisionalName: text(newsletter.provisionalName), strategicRole: text(newsletter.strategicRole), periodicity: text(newsletter.periodicity), startPhase: text(newsletter.startPhase), territories: list(newsletter.territories, "newsletter-territory"), predominantStructure: text(newsletter.predominantStructure), ctaGuideline: text(newsletter.ctaGuideline) },
    predominantStructure: text(r.predominantStructure), languageDirection: text(r.languageDirection) || list(r.languageStructures, "legacy-language").map((item) => item.value).join("\n"), languageRestrictions: list(r.languageRestrictions, "language-restriction"), visualDirection: text(r.visualDirection) || text(r.visualStrategy), visualElements: list(r.visualElements, "visual-element"), visualRestrictions: list(r.visualRestrictions, "visual-restriction"), visualReferences: Array.isArray(r.visualReferences) ? r.visualReferences.slice(0, 3).map((item, index) => { const v = record(item); return { id: id(v.id, `visual-reference-${index}`), image: text(v.image), title: text(v.title) }; }) : [],
    acquisitionGuideline: text(r.acquisitionGuideline), commentsGuideline: text(r.commentsGuideline), privateMessagesGuideline: text(r.privateMessagesGuideline), privateMessageSteps: list(r.privateMessageSteps, "message-step"), conversionStages: { discovery: stage(conversions.discovery), problem: stage(conversions.problem), commercial: stage(conversions.commercial) }, ctaGuideline: text(r.ctaGuideline), ecosystemRole: text(r.ecosystemRole), receivesFrom: list(r.receivesFrom, "origin"), directsTo: list(r.directsTo, "destination"), contentAdaptation: text(r.contentAdaptation),
    indicatorCategories: Array.isArray(r.indicatorCategories) ? r.indicatorCategories.map((item, index) => { const c = record(item); return { id: id(c.id, `indicator-category-${index}`), name: text(c.name), indicators: list(c.indicators, `indicator-${index}`) }; }) : [], references: Array.isArray(r.references) ? r.references.map((item, index) => { const ref = record(item); return { id: id(ref.id, `reference-${index}`), title: text(ref.title), link: text(ref.link) }; }) : [],
  };
}

const inputClass = "w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none transition placeholder:text-slate-400 focus:border-slate-400 focus:ring-4 focus:ring-slate-100";
const newId = () => typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : `linkedin-${Date.now()}-${Math.random().toString(36).slice(2)}`;

function Section({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><h2 className="text-base font-semibold text-slate-950">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{description}</p><div className="mt-5 space-y-5">{children}</div></section>; }
function Field({ label, children, help }: { label: string; children: ReactNode; help?: string }) { return <div><label className="mb-2 block text-sm font-semibold text-slate-700">{label}</label>{children}{help ? <p className="mt-2 text-xs leading-5 text-slate-500">{help}</p> : null}</div>; }
function TextList({ items, onChange, onAdd, addLabel, placeholder }: { items: LinkedInTextItem[]; onChange: (items: LinkedInTextItem[]) => void; onAdd: () => void; addLabel: string; placeholder?: string }) { return <div className="space-y-3">{items.map((item) => <div key={item.id} className="flex items-start gap-2"><input aria-label={placeholder || addLabel} value={item.value} onChange={(e) => onChange(items.map((current) => current.id === item.id ? { ...current, value: e.target.value } : current))} placeholder={placeholder} className={inputClass}/><button type="button" onClick={() => onChange(items.filter((current) => current.id !== item.id))} className="rounded-full px-3 py-3 text-sm font-semibold text-red-500 hover:bg-red-50">Excluir</button></div>)}<button type="button" onClick={onAdd} className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-950 hover:text-white">+ {addLabel}</button></div>; }

type Props = { data: LinkedInData; setData: Dispatch<SetStateAction<LinkedInData>>; clientSlug: string; presentationHref: string; planningProjectId: string; isSaving: boolean; isDisabled: boolean; onSave: () => void };
export default function LinkedInForm({ data, setData, clientSlug, presentationHref, planningProjectId, isSaving, isDisabled, onSave }: Props) {
  const [uploads, setUploads] = useState<Record<string, string>>({});
  const set = <K extends keyof LinkedInData>(key: K, value: LinkedInData[K]) => setData((current) => ({ ...current, [key]: value }));
  async function upload(event: ChangeEvent<HTMLInputElement>, key: string, category: "profile" | "references", apply: (url: string) => void) { const file = event.target.files?.[0]; if (!file) return; setUploads((v) => ({ ...v, [key]: "Enviando..." })); try { const result = await uploadPlanningMedia({ file, planningProjectId, category }); apply(result.url); setUploads((v) => ({ ...v, [key]: "" })); } catch (error) { setUploads((v) => ({ ...v, [key]: error instanceof Error ? error.message : "Falha no upload." })); } finally { event.target.value = ""; } }
  const updateTextList = (key: "objectives" | "languageRestrictions" | "visualElements" | "visualRestrictions" | "privateMessageSteps" | "receivesFrom" | "directsTo", items: LinkedInTextItem[]) => set(key, items);
  const addText = (key: Parameters<typeof updateTextList>[0]) => set(key, [...data[key], { id: newId(), value: "" }]);
  const previewAbout = data.aboutProfile.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim() || "A seção Sobre aparecerá aqui conforme o conteúdo for preenchido.";
  const formats = ["Texto autoral", "Carrossel em documento", "Vídeo nativo", "Newsletter"];
  return <div className="mt-6 space-y-6">
    <Section title="Visão estratégica do LinkedIn" description="Concentre o papel profissional do canal e seus objetivos centrais dentro do planejamento.">
      <Field label="Papel estratégico do LinkedIn"><RichTextEditor value={data.strategicRole} onChange={(value) => set("strategicRole", value)} placeholder=""/></Field>
      <Field label="Objetivos principais" help="Priorize até três objetivos centrais para o canal."><TextList items={data.objectives} onChange={(items) => updateTextList("objectives", items)} onAdd={() => addText("objectives")} addLabel="Adicionar objetivo"/></Field>
    </Section>
    <Section title="Perfil profissional do LinkedIn" description="Configure as principais informações do perfil e visualize como elas serão apresentadas profissionalmente.">
      <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="aspect-[4/1] bg-slate-100">{data.profileCover ? <img src={data.profileCover} alt="Capa do perfil" className="h-full w-full object-cover"/> : null}</div><div className="relative px-5 pb-5 pt-14 sm:px-7"><div className="absolute -top-12 h-24 w-24 overflow-hidden rounded-full border-4 border-white bg-slate-900 text-white">{data.profilePhoto ? <img src={data.profilePhoto} alt="Foto do perfil" className="h-full w-full object-cover"/> : <span className="flex h-full items-center justify-center text-xs">Foto</span>}</div><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-xl font-semibold text-slate-950">{data.profileName || "Nome do perfil"}</h3><p className="mt-1 text-sm text-slate-700">{data.professionalTitle || "Título profissional"}</p><p className="mt-1 text-xs text-slate-500">{data.location || "Localização"}{data.currentCompany ? ` · ${data.currentCompany}` : ""}</p><p className="mt-2 text-xs font-medium text-blue-700">{data.followers || "0"} seguidores · {data.connections || "0"} conexões</p></div><div aria-hidden="true" className="flex gap-2"><span className="rounded-full bg-blue-700 px-4 py-2 text-xs font-semibold text-white">Conectar</span><span className="rounded-full border border-blue-700 px-4 py-2 text-xs font-semibold text-blue-700">Mensagem</span></div></div><p className="mt-5 line-clamp-3 text-sm leading-6 text-slate-600">{previewAbout}</p>{data.featuredItems.some((item) => item.name || item.imageUrl) ? <div className="mt-4 flex gap-3 overflow-hidden">{data.featuredItems.slice(0,2).map((item) => <div key={item.id} className="min-w-0 flex-1 rounded-xl border border-slate-200 p-3 text-xs font-semibold text-slate-700">{item.name || "Item em destaque"}</div>)}</div> : null}</div></div>
      <div className="grid gap-5 md:grid-cols-2"><Field label="Imagem de capa"><input aria-label="Enviar imagem de capa" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => upload(e,"cover","profile",(url)=>set("profileCover",url))} className={inputClass}/>{uploads.cover ? <p className="mt-2 text-xs text-slate-500">{uploads.cover}</p> : null}{data.profileCover ? <button type="button" onClick={() => set("profileCover","")} className="mt-2 text-xs font-semibold text-red-500">Remover capa</button> : null}</Field><Field label="Foto do perfil"><input aria-label="Enviar foto do perfil" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => upload(e,"photo","profile",(url)=>set("profilePhoto",url))} className={inputClass}/>{uploads.photo ? <p className="mt-2 text-xs text-slate-500">{uploads.photo}</p> : null}{data.profilePhoto ? <button type="button" onClick={() => set("profilePhoto","")} className="mt-2 text-xs font-semibold text-red-500">Remover foto</button> : null}</Field></div>
      <div className="grid gap-4 md:grid-cols-2"><Field label="Nome do perfil"><input value={data.profileName} onChange={(e)=>set("profileName",e.target.value)} className={inputClass}/></Field><Field label="Título profissional" help="Apresente a atuação, o público e a transformação profissional de forma objetiva."><input value={data.professionalTitle} onChange={(e)=>set("professionalTitle",e.target.value)} className={inputClass}/></Field><Field label="Localização (opcional)"><input value={data.location} onChange={(e)=>set("location",e.target.value)} className={inputClass}/></Field><Field label="Empresa ou atuação atual (opcional)"><input value={data.currentCompany} onChange={(e)=>set("currentCompany",e.target.value)} className={inputClass}/></Field><Field label="Seguidores"><input type="number" min="0" value={data.followers} onChange={(e)=>set("followers",e.target.value)} className={inputClass}/></Field><Field label="Conexões"><input type="number" min="0" value={data.connections} onChange={(e)=>set("connections",e.target.value)} className={inputClass}/></Field></div><p className="text-xs text-slate-500">Os números são utilizados apenas na simulação visual do perfil e não representam metas estratégicas.</p><Field label="Seção Sobre" help="Estruture o texto com contexto do público, visão estratégica, atuação, trajetória e próximo passo."><RichTextEditor value={data.aboutProfile} onChange={(value)=>set("aboutProfile",value)} placeholder=""/></Field>
    </Section>
    <Section title="Itens em destaque" description="Organize os conteúdos, páginas e ofertas que devem receber maior visibilidade no perfil.">
      {data.featuredItems.map((item,index)=><div key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="grid gap-4 md:grid-cols-2"><Field label="Nome"><input value={item.name} onChange={(e)=>set("featuredItems",data.featuredItems.map(v=>v.id===item.id?{...v,name:e.target.value}:v))} className={inputClass}/></Field><Field label="Destino ou URL"><input value={item.destination} onChange={(e)=>set("featuredItems",data.featuredItems.map(v=>v.id===item.id?{...v,destination:e.target.value}:v))} className={inputClass}/></Field><Field label="Função"><textarea rows={3} value={item.purpose} onChange={(e)=>set("featuredItems",data.featuredItems.map(v=>v.id===item.id?{...v,purpose:e.target.value}:v))} className={inputClass}/></Field><Field label="CTA"><input value={item.cta} onChange={(e)=>set("featuredItems",data.featuredItems.map(v=>v.id===item.id?{...v,cta:e.target.value}:v))} className={inputClass}/></Field><Field label="Imagem ou miniatura (opcional)"><input aria-label="Enviar miniatura" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e)=>upload(e,`featured-${item.id}`,"references",(url)=>set("featuredItems",data.featuredItems.map(v=>v.id===item.id?{...v,imageUrl:url}:v)))} className={inputClass}/>{item.imageUrl?<button type="button" onClick={()=>set("featuredItems",data.featuredItems.map(v=>v.id===item.id?{...v,imageUrl:""}:v))} className="mt-2 text-xs font-semibold text-red-500">Remover imagem</button>:null}</Field></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={index===0} onClick={()=>{const n=[...data.featuredItems];[n[index-1],n[index]]=[n[index],n[index-1]];set("featuredItems",n)}} className="rounded-full border px-3 py-2 text-xs disabled:opacity-40">Subir</button><button type="button" disabled={index===data.featuredItems.length-1} onClick={()=>{const n=[...data.featuredItems];[n[index],n[index+1]]=[n[index+1],n[index]];set("featuredItems",n)}} className="rounded-full border px-3 py-2 text-xs disabled:opacity-40">Descer</button><button type="button" onClick={()=>set("featuredItems",data.featuredItems.filter(v=>v.id!==item.id))} className="rounded-full px-3 py-2 text-xs font-semibold text-red-500">Excluir</button></div></div>)}<button type="button" onClick={()=>set("featuredItems",[...data.featuredItems,{id:newId(),name:"",purpose:"",destination:"",cta:"",imageUrl:""}])} className="rounded-full border px-4 py-2 text-sm font-semibold">+ Adicionar item em destaque</button>
    </Section>
    <Section title="Formatos e frequência" description="Defina a cadência de publicação por formato.">
      {data.frequencyItems.map(item=><div key={item.id} className="grid gap-4 rounded-2xl border border-slate-200 p-4 md:grid-cols-2 lg:grid-cols-5"><Field label="Formato"><select value={item.format} onChange={(e)=>set("frequencyItems",data.frequencyItems.map(v=>v.id===item.id?{...v,format:e.target.value}:v))} className={inputClass}>{item.format&&!formats.includes(item.format)?<option value={item.format}>{item.format} (histórico)</option>:<option value="">Selecione</option>}{formats.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Quantidade"><input type="number" min="0" value={item.quantity} onChange={(e)=>set("frequencyItems",data.frequencyItems.map(v=>v.id===item.id?{...v,quantity:e.target.value}:v))} className={inputClass}/></Field><Field label="Período"><select value={item.period} onChange={(e)=>set("frequencyItems",data.frequencyItems.map(v=>v.id===item.id?{...v,period:e.target.value}:v))} className={inputClass}>{["por dia","por semana","por quinzena","por mês","por ciclo","outro"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Observação"><input value={item.observation} onChange={(e)=>set("frequencyItems",data.frequencyItems.map(v=>v.id===item.id?{...v,observation:e.target.value}:v))} className={inputClass}/></Field><button type="button" onClick={()=>set("frequencyItems",data.frequencyItems.filter(v=>v.id!==item.id))} className="self-end rounded-full px-3 py-3 text-sm font-semibold text-red-500">Excluir</button></div>)}<button type="button" onClick={()=>set("frequencyItems",[...data.frequencyItems,{id:newId(),format:"",quantity:"",period:"por semana",observation:""}])} className="rounded-full border px-4 py-2 text-sm font-semibold">+ Adicionar formato</button>
    </Section>
    <Section title="Estratégia editorial e newsletter" description="Organize os territórios, as abordagens e os conteúdos de aprofundamento específicos do LinkedIn.">
      <Field label="Territórios editoriais"><div className="space-y-4">{data.editorialTerritories.map(t=><div key={t.id} className="rounded-2xl border p-4"><div className="grid gap-4 md:grid-cols-3"><input aria-label="Nome do território" placeholder="Nome do território" value={t.name} onChange={(e)=>set("editorialTerritories",data.editorialTerritories.map(v=>v.id===t.id?{...v,name:e.target.value}:v))} className={inputClass}/><textarea aria-label="Função do território" placeholder="Função" rows={2} value={t.purpose} onChange={(e)=>set("editorialTerritories",data.editorialTerritories.map(v=>v.id===t.id?{...v,purpose:e.target.value}:v))} className={inputClass}/><textarea aria-label="Descrição do território" placeholder="Descrição curta" rows={2} value={t.description} onChange={(e)=>set("editorialTerritories",data.editorialTerritories.map(v=>v.id===t.id?{...v,description:e.target.value}:v))} className={inputClass}/></div><div className="mt-3"><TextList items={t.recommendedFormats} onChange={(items)=>set("editorialTerritories",data.editorialTerritories.map(v=>v.id===t.id?{...v,recommendedFormats:items}:v))} onAdd={()=>set("editorialTerritories",data.editorialTerritories.map(v=>v.id===t.id?{...v,recommendedFormats:[...v.recommendedFormats,{id:newId(),value:""}]}:v))} addLabel="Adicionar formato recomendado"/></div><button type="button" onClick={()=>set("editorialTerritories",data.editorialTerritories.filter(v=>v.id!==t.id))} className="mt-3 text-sm font-semibold text-red-500">Excluir território</button></div>)}</div><button type="button" onClick={()=>set("editorialTerritories",[...data.editorialTerritories,{id:newId(),name:"",purpose:"",description:"",recommendedFormats:[]}])} className="mt-3 rounded-full border px-4 py-2 text-sm font-semibold">+ Adicionar território</button></Field>
      <Field label="Abordagem editorial central" help="Registre a lógica predominante de construção dos conteúdos e o nível de aprofundamento esperado."><RichTextEditor value={data.editorialApproach} onChange={(value)=>set("editorialApproach",value)} placeholder=""/></Field>
      <div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-semibold">Newsletter do LinkedIn</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Nome provisório"><input value={data.newsletter.provisionalName} onChange={(e)=>set("newsletter",{...data.newsletter,provisionalName:e.target.value})} className={inputClass}/></Field><Field label="Periodicidade"><select value={data.newsletter.periodicity} onChange={(e)=>set("newsletter",{...data.newsletter,periodicity:e.target.value})} className={inputClass}><option value="">Selecione</option>{["semanal","quinzenal","mensal","outro"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Papel estratégico"><textarea rows={3} value={data.newsletter.strategicRole} onChange={(e)=>set("newsletter",{...data.newsletter,strategicRole:e.target.value})} className={inputClass}/></Field><Field label="Data ou fase de início"><input value={data.newsletter.startPhase} onChange={(e)=>set("newsletter",{...data.newsletter,startPhase:e.target.value})} className={inputClass}/></Field></div><div className="mt-4"><Field label="Territórios da newsletter"><TextList items={data.newsletter.territories} onChange={(items)=>set("newsletter",{...data.newsletter,territories:items})} onAdd={()=>set("newsletter",{...data.newsletter,territories:[...data.newsletter.territories,{id:newId(),value:""}]})} addLabel="Adicionar território"/></Field></div><div className="mt-4"><Field label="Estrutura predominante"><RichTextEditor value={data.newsletter.predominantStructure} onChange={(value)=>set("newsletter",{...data.newsletter,predominantStructure:value})} placeholder=""/></Field></div><div className="mt-4"><Field label="Diretriz de CTA"><textarea rows={3} value={data.newsletter.ctaGuideline} onChange={(e)=>set("newsletter",{...data.newsletter,ctaGuideline:e.target.value})} className={inputClass}/></Field></div></div>
    </Section>
    <Section title="Estrutura, linguagem e direção visual" description="Defina como os conteúdos organizam o raciocínio, como o perfil se comunica e como a presença visual sustenta a autoridade.">
      <Field label="Estrutura predominante"><RichTextEditor value={data.predominantStructure} onChange={(value)=>set("predominantStructure",value)} placeholder=""/></Field><Field label="Direção de linguagem"><RichTextEditor value={data.languageDirection} onChange={(value)=>set("languageDirection",value)} placeholder=""/></Field><Field label="O que evitar na linguagem"><TextList items={data.languageRestrictions} onChange={(items)=>updateTextList("languageRestrictions",items)} onAdd={()=>addText("languageRestrictions")} addLabel="Adicionar orientação"/></Field><Field label="Direção visual do LinkedIn"><RichTextEditor value={data.visualDirection} onChange={(value)=>set("visualDirection",value)} placeholder=""/></Field><div className="grid gap-5 md:grid-cols-2"><Field label="Elementos visuais"><TextList items={data.visualElements} onChange={(items)=>updateTextList("visualElements",items)} onAdd={()=>addText("visualElements")} addLabel="Adicionar elemento"/></Field><Field label="O que evitar visualmente"><TextList items={data.visualRestrictions} onChange={(items)=>updateTextList("visualRestrictions",items)} onAdd={()=>addText("visualRestrictions")} addLabel="Adicionar orientação visual"/></Field></div><Field label="Referências visuais (até três)"><div className="grid gap-4 sm:grid-cols-3">{data.visualReferences.map(ref=><div key={ref.id} className="rounded-2xl border p-3">{ref.image?<img src={ref.image} alt={ref.title||"Referência visual"} className="mb-3 aspect-video w-full rounded-xl object-cover"/>:null}<input aria-label="Título da referência visual" placeholder="Título ou descrição" value={ref.title} onChange={(e)=>set("visualReferences",data.visualReferences.map(v=>v.id===ref.id?{...v,title:e.target.value}:v))} className={inputClass}/><input aria-label="Enviar referência visual" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e)=>upload(e,`visual-${ref.id}`,"references",(url)=>set("visualReferences",data.visualReferences.map(v=>v.id===ref.id?{...v,image:url}:v)))} className="mt-2 block w-full text-xs"/><button type="button" onClick={()=>set("visualReferences",data.visualReferences.filter(v=>v.id!==ref.id))} className="mt-2 text-xs font-semibold text-red-500">Remover</button></div>)}{data.visualReferences.length<3?<button type="button" onClick={()=>set("visualReferences",[...data.visualReferences,{id:newId(),image:"",title:""}])} className="rounded-2xl border border-dashed p-4 text-sm font-semibold">+ Adicionar referência</button>:null}</div></Field>
    </Section>
    <Section title="Aquisição, relacionamento e conversão" description="Registre como o perfil atrai oportunidades, conduz interações e encaminha contatos com intenção comercial.">
      <div className="grid gap-4 md:grid-cols-3">{[["Diretriz de aquisição","acquisitionGuideline"],["Diretriz de comentários","commentsGuideline"],["Diretriz de mensagens privadas","privateMessagesGuideline"]].map(([label,key])=><Field key={key} label={label}><textarea rows={4} value={data[key as "acquisitionGuideline"]} onChange={(e)=>set(key as "acquisitionGuideline",e.target.value)} className={inputClass}/></Field>)}</div><Field label="Etapas da mensagem privada"><TextList items={data.privateMessageSteps} onChange={(items)=>updateTextList("privateMessageSteps",items)} onAdd={()=>addText("privateMessageSteps")} addLabel="Adicionar etapa"/></Field><div className="grid gap-4 md:grid-cols-3">{([["Descoberta e aprofundamento","discovery"],["Reconhecimento do problema","problem"],["Intenção comercial","commercial"]] as const).map(([label,key])=><div key={key} className="rounded-2xl border p-4"><h3 className="text-sm font-semibold">{label}</h3><input aria-label={`Ação esperada — ${label}`} placeholder="Ação esperada" value={data.conversionStages[key].action} onChange={(e)=>set("conversionStages",{...data.conversionStages,[key]:{...data.conversionStages[key],action:e.target.value}})} className={`${inputClass} mt-3`}/><input aria-label={`Destino — ${label}`} placeholder="Destino ou continuidade" value={data.conversionStages[key].destination} onChange={(e)=>set("conversionStages",{...data.conversionStages,[key]:{...data.conversionStages[key],destination:e.target.value}})} className={`${inputClass} mt-3`}/></div>)}</div><Field label="Diretriz de CTA"><textarea rows={3} value={data.ctaGuideline} onChange={(e)=>set("ctaGuideline",e.target.value)} className={inputClass}/></Field>
    </Section>
    <Section title="Integração com outros canais" description="Registre como os conteúdos chegam ao LinkedIn, como são reinterpretados e para onde direcionam o público.">
      <Field label="Papel no ecossistema"><textarea rows={3} value={data.ecosystemRole} onChange={(e)=>set("ecosystemRole",e.target.value)} className={inputClass}/></Field><div className="grid gap-5 md:grid-cols-2"><Field label="Recebe audiência ou conteúdo de"><TextList items={data.receivesFrom} onChange={(items)=>updateTextList("receivesFrom",items)} onAdd={()=>addText("receivesFrom")} addLabel="Adicionar origem"/></Field><Field label="Direciona audiência para"><TextList items={data.directsTo} onChange={(items)=>updateTextList("directsTo",items)} onAdd={()=>addText("directsTo")} addLabel="Adicionar destino"/></Field></div><Field label="Diretriz de adaptação de conteúdo"><RichTextEditor value={data.contentAdaptation} onChange={(value)=>set("contentAdaptation",value)} placeholder=""/></Field>
    </Section>
    <Section title="Indicadores principais" description="Agrupe apenas os indicadores relevantes para acompanhar autoridade, interesse e maturidade comercial.">
      {data.indicatorCategories.map(category=><div key={category.id} className="rounded-2xl border p-4"><input aria-label="Nome da categoria" placeholder="Nome da categoria" value={category.name} onChange={(e)=>set("indicatorCategories",data.indicatorCategories.map(v=>v.id===category.id?{...v,name:e.target.value}:v))} className={inputClass}/><div className="mt-3"><TextList items={category.indicators} onChange={(items)=>set("indicatorCategories",data.indicatorCategories.map(v=>v.id===category.id?{...v,indicators:items}:v))} onAdd={()=>set("indicatorCategories",data.indicatorCategories.map(v=>v.id===category.id?{...v,indicators:[...v.indicators,{id:newId(),value:""}]}:v))} addLabel="Adicionar indicador"/></div><button type="button" onClick={()=>set("indicatorCategories",data.indicatorCategories.filter(v=>v.id!==category.id))} className="mt-3 text-sm font-semibold text-red-500">Excluir categoria</button></div>)}<button type="button" onClick={()=>set("indicatorCategories",[...data.indicatorCategories,{id:newId(),name:"",indicators:[]}])} className="rounded-full border px-4 py-2 text-sm font-semibold">+ Adicionar categoria</button>
    </Section>
    <Section title="Referências internas · Uso interno" description="Links e referências de apoio não exibidos na apresentação ao cliente.">{data.references.map(ref=><div key={ref.id} className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input aria-label="Título da referência" placeholder="Título" value={ref.title} onChange={(e)=>set("references",data.references.map(v=>v.id===ref.id?{...v,title:e.target.value}:v))} className={inputClass}/><input aria-label="Link da referência" placeholder="Link" value={ref.link} onChange={(e)=>set("references",data.references.map(v=>v.id===ref.id?{...v,link:e.target.value}:v))} className={inputClass}/><button type="button" onClick={()=>set("references",data.references.filter(v=>v.id!==ref.id))} className="text-sm font-semibold text-red-500">Excluir</button></div>)}<button type="button" onClick={()=>set("references",[...data.references,{id:newId(),title:"",link:""}])} className="rounded-full border px-4 py-2 text-sm font-semibold">+ Adicionar referência</button></Section>
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><Link href={`/admin/clientes/${clientSlug}`} className="rounded-full border border-slate-200 px-5 py-3 text-center text-sm font-semibold text-slate-700">Voltar</Link><div className="flex flex-col gap-3 sm:flex-row"><Link href={presentationHref} target="_blank" className="rounded-full border border-slate-200 px-5 py-3 text-center text-sm font-semibold text-slate-700">Ver apresentação</Link><button type="button" disabled={isDisabled||isSaving} onClick={onSave} className="rounded-full bg-slate-950 px-6 py-3 text-sm font-semibold text-white disabled:opacity-50">{isSaving?"Salvando...":"Salvar planejamento"}</button></div></div>
  </div>;
}
